### PR TITLE
Kb complete order

### PR DESCRIPTION
**Pull request by klboyd**
# Description
Add things to the order and watch the shopping cart fill up. Then you can complete your order! Hot dang!

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
# Testing Instructions

1. Add items to your cart
1. Click over to shopping cart and select complete your order
1. Choose your payment type
1. Confirm payment type and complete order

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by melliemuse — DISMISSED** [review]
Hot dang! Works great!

**Review by rdbishop19 — DISMISSED** [review]
I'm going to buy so match useless sh*t now 🛒 🛒 🛒

**Review by CassieBoyd — APPROVED** [review]
It does the thing, Zhu Li!

**Review by rdbishop19 — APPROVED** [review]
finally. the view that the shopping cart link deserves... 🖖

**Pull request merged**
